# Generated by Django 5.2.8 on 2025-11-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
