# Generated by Django 5.2.8 on 2025-11-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
